/*
 * File: app/view/frmGroupMember.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.frmGroupMember', {
    extend: 'Ext.window.Window',
    alias: 'widget.frmGroupMember',

    requires: [
        'Ext.form.field.Text',
        'Ext.container.Container',
        'Ext.button.Button'
    ],

    height: 150,
    id: 'frmGroupMember',
    itemId: 'frmGroupMember',
    width: 400,
    constrain: true,
    bodyPadding: '20 0 0 20',
    title: 'カスタムスケジュール',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    id: 'txtGroupMember',
                    itemId: 'txtGroupMember',
                    width: 350,
                    fieldLabel: 'グループ名'
                },
                {
                    xtype: 'container',
                    margin: '0 0 0 220',
                    items: [
                        {
                            xtype: 'button',
                            hidden: true,
                            id: 'btnGroupMemberDelete',
                            itemId: 'btnGroupMemberDelete',
                            margin: '0 10 0 0',
                            width: 60,
                            text: '削除'
                        },
                        {
                            xtype: 'button',
                            id: 'btnGroupMemberSave',
                            itemId: 'btnGroupMemberSave',
                            width: 60,
                            text: '保存'
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            id: 'btnGroupMemberCancel',
                            itemId: 'btnGroupMemberCancel',
                            margin: '0 0 0 10',
                            width: 60,
                            text: 'キャンセル'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});