/*
 * File: app/model/MdCustomGroup.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.MdCustomGroup', {
    extend: 'Ext.data.Model',
    alias: 'model.MdCustomGroup',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'CUSTOM_ID'
        },
        {
            name: 'GROUP_NAME'
        }
    ]
});