/*
 * File: app/store/StCriticalLevelsSearch.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.StCriticalLevelsSearch', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.MdGeneral'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'MyApp.model.MdGeneral',
            storeId: 'StCriticalLevelsSearch',
            data: [
                {
                    VALUE: -1,
                    TITLE: '---'
                },
                {
                    VALUE: 1,
                    TITLE: 1
                },
                {
                    VALUE: 2,
                    TITLE: 2
                },
                {
                    VALUE: 3,
                    TITLE: 3
                },
                
            ]
        }, cfg)]);
    }
});