/*
 * File: app/view/FrmGroupCircle.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.FrmGroupCircle', {
    extend: 'Ext.window.Window',

    requires: [
        'MyApp.view.UcTreeMember',
        'Ext.tree.Panel',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.button.Button',
        'Ext.form.Label',
        'Ext.form.field.ComboBox'
    ],

    height: 550,
    id: 'frmGroupCircle',
    itemId: 'frmGroupCircle',
    width: 641,
    constrain: true,
    resizable: false,
    icon: 'resources/images/ACcommIcon.ico',
    title: 'サークル',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    border: false,
                    height: 529,
                    width: 637,
                    layout: 'absolute',
                    bodyStyle: {
                        background: 'none !important'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 70,
                            id: 'txtGroupCircle',
                            itemId: 'txtGroupCircle',
                            width: 610,
                            fieldLabel: ' 新サークル名',
                            labelWidth: 110
                        },
                        {
                            xtype: 'container',
                            x: 10,
                            y: 120,
                            weight: 270,
                            height: 360,
                            width: 270,
                            items: [
                                {
                                    xtype: 'ucTreeMember'
                                }
                            ]
                        },
                        {
                            xtype: 'radiogroup',
                            x: 10,
                            y: 490,
                            itemId: 'rgrRole',
                            width: 240,
                            fieldLabel: '',
                            items: [
                                {
                                    xtype: 'radiofield',
                                    itemId: 'rdoAdmin',
                                    name: 'rdo',
                                    boxLabel: '管理者',
                                    inputValue: '1'
                                },
                                {
                                    xtype: 'radiofield',
                                    itemId: 'rdoMember',
                                    name: 'rdo',
                                    boxLabel: 'メンバー',
                                    checked: true,
                                    inputValue: '2'
                                },
                                {
                                    xtype: 'radiofield',
                                    itemId: 'rdoReadOnly',
                                    fieldLabel: '',
                                    name: 'rdo',
                                    boxLabel: '閲覧のみ',
                                    inputValue: '3'
                                }
                            ]
                        },
                        {
                            xtype: 'radiogroup',
                            x: 125,
                            y: 10,
                            itemId: 'rgrFormStatus',
                            width: 240,
                            fieldLabel: '',
                            items: [
                                {
                                    xtype: 'radiofield',
                                    id: 'rdoAddNew',
                                    itemId: 'rdoAddNew',
                                    name: 'rdostatus',
                                    boxLabel: '新規',
                                    checked: true,
                                    inputValue: '2'
                                },
                                {
                                    xtype: 'radiofield',
                                    id: 'rdoEdit',
                                    itemId: 'rdoEdit',
                                    margin: '0 0 0 -40',
                                    fieldLabel: '',
                                    name: 'rdostatus',
                                    boxLabel: '編集',
                                    inputValue: '3'
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            x: 440,
                            y: 490,
                            id: 'btnSaveCircle',
                            itemId: 'btnSaveCircle',
                            width: 80,
                            text: '保存'
                        },
                        {
                            xtype: 'button',
                            x: 540,
                            y: 490,
                            itemId: 'btnClose',
                            width: 80,
                            text: '閉じる'
                        },
                        {
                            xtype: 'button',
                            x: 340,
                            y: 490,
                            disabled: true,
                            id: 'btnDelete',
                            itemId: 'btnDelete',
                            width: 80,
                            text: '削除'
                        },
                        {
                            xtype: 'button',
                            x: 290,
                            y: 210,
                            height: 30,
                            id: 'btnMoveMember',
                            itemId: 'btnMoveMember',
                            width: 40,
                            text: '→'
                        },
                        {
                            xtype: 'panel',
                            x: 340,
                            y: 120,
                            height: 360,
                            id: 'pnlMovedMember',
                            itemId: 'pnlMovedMember',
                            width: 280,
                            autoScroll: true,
                            title: ''
                        },
                        {
                            xtype: 'label',
                            x: 10,
                            y: 100,
                            text: 'スタッフ:'
                        },
                        {
                            xtype: 'label',
                            x: 340,
                            y: 100,
                            text: '参加者:'
                        },
                        {
                            xtype: 'combobox',
                            x: 10,
                            y: 40,
                            disabled: true,
                            id: 'cboCircleName',
                            itemId: 'cboCircleName',
                            width: 610,
                            fieldLabel: '編集前のサークル名',
                            labelWidth: 110,
                            editable: false,
                            displayField: 'TITLE',
                            queryMode: 'local',
                            store: 'StCircleGroupEdit',
                            valueField: 'VALUE'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});