/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'Ext.form.Panel',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.toolbar.Separator',
        'Ext.form.field.ComboBox',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Column',
        'Ext.form.FieldSet',
        'Ext.form.Label',
        'Ext.form.field.TextArea'
    ],

    itemId: 'mainview',
    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    hidden: true,
                    id: 'frmMain',
                    itemId: 'frmMain',
                    layout: 'border',
                    bodyPadding: 10,
                    icon: 'resources/images/commIcon.ico',
                    title: 'メイン',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            hidden: true,
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'メッセージ(&M)',
                                    menu: {
                                        xtype: 'menu',
                                        width: 200,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                icon: '../resources/images/s_newmaking.ico',
                                                text: '新規作成'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: '雛形から新規作成'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                icon: '../resources/images/s_unattestation.ico',
                                                text: '受信メッセージ'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'mniMainExit',
                                                text: 'アプリケーションの終了(&X)'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    text: '出退勤(&W)',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    text: 'アプリ(&A)',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    text: '帳票',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    text: 'ツール(&T)',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    text: 'その他(&O)',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    text: '入力',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Menu Item'
                                            }
                                        ]
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'btnMainAddMsg',
                                    width: 60,
                                    icon: 'resources/images/s_newmaking.ico',
                                    iconAlign: 'top',
                                    text: '新規作成',
                                    tooltip: 'Ctr + M'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnMainSchedule',
                                    icon: 'resources/images/s_new_schedule.ico',
                                    iconAlign: 'top',
                                    text: 'スケジュール',
                                    tooltip: 'Ctr + S'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnMainSchedule1',
                                    icon: 'resources/images/s_new_schedule.ico',
                                    iconAlign: 'top',
                                    text: 'スケジュール New',
                                    tooltip: 'Ctr + S'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnCircle',
                                    icon: 'resources/images/circle.ico',
                                    iconAlign: 'top',
                                    text: '新規サークル',
                                    tooltip: 'Ctr + G'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnWork',
                                    icon: 'resources/images/worktime.ico',
                                    iconAlign: 'top',
                                    text: '出退勤',
                                    tooltip: 'Ctr + D'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnQuickSearch',
                                    itemId: 'btnQuickSearch',
                                    width: 90,
                                    icon: 'resources/images/downicon.ico',
                                    text: 'クイック検索',
                                    tooltip: 'Ctr + F2'
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'cboTheme',
                                    style: {
                                        float: 'right',
                                        left: 'auto !important',
                                        right: '85px !important'
                                    },
                                    width: 120,
                                    fieldLabel: 'テーマ',
                                    labelWidth: 40,
                                    editable: false,
                                    displayField: 'TITLE',
                                    queryMode: 'local',
                                    store: 'StTheme',
                                    valueField: 'VALUE'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnMainLogOut',
                                    style: {
                                        float: 'right',
                                        left: 'auto !important',
                                        right: '5px !important'
                                    },
                                    width: 70,
                                    icon: 'resources/images/logout.ico',
                                    iconAlign: 'top',
                                    text: 'ログアウト'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            dock: 'bottom',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    style: {
                                        'border-top': 0
                                    },
                                    layout: {
                                        type: 'hbox',
                                        padding: 5
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            text: 'ステータス'
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'panel',
                            region: 'center',
                            border: false,
                            layout: 'border',
                            collapsible: false,
                            items: [
                                {
                                    xtype: 'tabpanel',
                                    region: 'west',
                                    width: 200,
                                    collapsible: true,
                                    title: 'フィルタリング',
                                    activeTab: 0,
                                    items: [
                                        {
                                            xtype: 'panel',
                                            autoScroll: true,
                                            layout: 'fit',
                                            title: 'サークル別',
                                            items: [
                                                {
                                                    xtype: 'treepanel',
                                                    setRootNode: function() {
                                                        if (this.getStore().autoLoad) {
                                                            this.callParent(arguments);
                                                        }
                                                    },
                                                    border: false,
                                                    id: 'tpnCircleGroup',
                                                    itemId: 'tpnCircleGroup',
                                                    autoScroll: true,
                                                    store: 'StCircleGroupTree',
                                                    displayField: 'TITLE',
                                                    viewConfig: {
                                                        rootVisible: false
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            layout: 'fit',
                                            title: '部署別',
                                            items: [
                                                {
                                                    xtype: 'treepanel',
                                                    setRootNode: function() {

                                                    },
                                                    id: 'tpnSenderGroup',
                                                    itemId: 'tpnSenderGroup',
                                                    store: 'StGroupMain',
                                                    displayField: 'name',
                                                    rootVisible: false,
                                                    viewConfig: {
                                                        id: 'tvwSenderGroup',
                                                        itemId: 'tvwSenderGroup'
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            layout: 'absolute',
                                            title: 'タグ',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    x: 150,
                                                    y: 10,
                                                    height: 75,
                                                    id: 'btnTagSearch',
                                                    itemId: 'btnTagSearch',
                                                    style: {
                                                        'z-index': '1000 !important'
                                                    },
                                                    width: 45,
                                                    text: '検索'
                                                },
                                                {
                                                    xtype: 'boxselect',
                                                    createNewOnBlur: true,
                                                    filterPickList: true,
                                                    growMin: 75,
                                                    growMax: 120,
                                                    x: 10,
                                                    y: 10,
                                                    id: 'cboTagSearch',
                                                    itemId: 'cboTagSearch',
                                                    maxHeight: 20,
                                                    width: 160,
                                                    displayField: 'TITLE',
                                                    multiSelect: true,
                                                    queryMode: 'local',
                                                    store: 'StTag',
                                                    valueField: 'VALUE'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    region: 'center',
                                    border: false,
                                    layout: 'border',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            region: 'north',
                                            split: true,
                                            border: false,
                                            height: 220,
                                            layout: 'border',
                                            bodyBorder: false,
                                            items: [
                                                {
                                                    xtype: 'gridpanel',
                                                    region: 'center',
                                                    id: 'grdMsg',
                                                    itemId: 'grdMsg',
                                                    forceFit: true,
                                                    store: 'StMessages',
                                                    dockedItems: [
                                                        {
                                                            xtype: 'pagingtoolbar',
                                                            dock: 'bottom',
                                                            displayInfo: true,
                                                            store: 'StMessages'
                                                        }
                                                    ],
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 30,
                                                            dataIndex: 'ATTACH',
                                                            text: '添付'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'MSG_ID',
                                                            text: '伝達ID'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'IMPORTANT_LEVEL',
                                                            text: '重要度'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 320,
                                                            dataIndex: 'MSG_TITLE',
                                                            text: '題名'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'RELEASE_DATE',
                                                            text: '受信日時'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'EXPILATION_DATE',
                                                            text: '期限'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'COMMENTDATE',
                                                            text: '最終更新日時'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'EMP_NAME',
                                                            text: '送信者'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'EMP_PROGRESS_TEXT',
                                                            text: '進捗'
                                                        }
                                                    ]
                                                }
                                            ],
                                            dockedItems: [
                                                {
                                                    xtype: 'panel',
                                                    dock: 'top',
                                                    border: false,
                                                    hidden: true,
                                                    id: 'pnlSearch',
                                                    itemId: 'pnlSearch',
                                                    dockedItems: [
                                                        {
                                                            xtype: 'fieldset',
                                                            dock: 'top',
                                                            padding: 0,
                                                            layout: 'table',
                                                            items: [
                                                                {
                                                                    xtype: 'combobox',
                                                                    id: 'cboMessageType',
                                                                    itemId: 'cboMessageType',
                                                                    margin: '0 10 0 10',
                                                                    width: 230,
                                                                    fieldLabel: 'メッセージタイプ',
                                                                    labelPad: 0,
                                                                    editable: false,
                                                                    displayField: 'TITLE',
                                                                    queryMode: 'local',
                                                                    store: 'StMessageType',
                                                                    valueField: 'VALUE'
                                                                },
                                                                {
                                                                    xtype: 'combobox',
                                                                    itemId: 'cboMessageStatus',
                                                                    margin: '0 10 0 0',
                                                                    width: 250,
                                                                    fieldLabel: 'メッセージステータス',
                                                                    labelWidth: 120,
                                                                    readOnly: true,
                                                                    editable: false,
                                                                    displayField: 'MSG_STATUS_TITLE',
                                                                    queryMode: 'local',
                                                                    store: 'StMessageStatus',
                                                                    valueField: 'MSG_STATUS_VALUE'
                                                                },
                                                                {
                                                                    xtype: 'combobox',
                                                                    id: 'cboSender',
                                                                    itemId: 'cboSender',
                                                                    margin: '0 10 0 0',
                                                                    width: 180,
                                                                    fieldLabel: '送信者:',
                                                                    labelPad: 0,
                                                                    labelWidth: 50,
                                                                    editable: false,
                                                                    displayField: 'EMP_NAME',
                                                                    queryMode: 'local',
                                                                    store: 'StEmployeesSearch',
                                                                    valueField: 'EMP_ID'
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    id: 'txtTitle',
                                                                    itemId: 'txtTitle',
                                                                    margin: '0 10 0 0',
                                                                    width: 180,
                                                                    fieldLabel: '題名',
                                                                    labelWidth: 30,
                                                                    enableKeyEvents: true
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    id: 'txtMessage',
                                                                    itemId: 'txtMessage',
                                                                    margin: '0 10 0 0',
                                                                    width: 200,
                                                                    fieldLabel: 'メッセージ:',
                                                                    labelWidth: 70,
                                                                    enableKeyEvents: true
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnMainSearchMsg',
                                                                    margin: '0 10 0 0',
                                                                    icon: 'resources/images/s_retrieval.ico',
                                                                    text: '検索'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            region: 'center',
                                            split: true,
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: 'border',
                                                    items: [
                                                        {
                                                            xtype: 'container',
                                                            region: 'north',
                                                            height: 50,
                                                            layout: 'column',
                                                            items: [
                                                                {
                                                                    xtype: 'container',
                                                                    columnWidth: 1,
                                                                    height: 50,
                                                                    padding: 5,
                                                                    items: [
                                                                        {
                                                                            xtype: 'label',
                                                                            padding: '0 5 0 0',
                                                                            text: '送信者:'
                                                                        },
                                                                        {
                                                                            xtype: 'label',
                                                                            itemId: 'lblEmpName',
                                                                            padding: '0 20 0 0'
                                                                        },
                                                                        {
                                                                            xtype: 'label',
                                                                            padding: '0 5 0 0',
                                                                            text: '受信日時:'
                                                                        },
                                                                        {
                                                                            xtype: 'label',
                                                                            itemId: 'lblReleaseDate',
                                                                            padding: '0 20 0 0'
                                                                        },
                                                                        {
                                                                            xtype: 'label',
                                                                            padding: '0 5 0 0',
                                                                            text: '進捗:'
                                                                        },
                                                                        {
                                                                            xtype: 'label',
                                                                            itemId: 'lblProgress',
                                                                            padding: '0 20 0 0'
                                                                        },
                                                                        {
                                                                            xtype: 'label',
                                                                            padding: '0 5 0 0',
                                                                            text: '重要度:'
                                                                        },
                                                                        {
                                                                            xtype: 'label',
                                                                            itemId: 'lblImportant',
                                                                            padding: '0 20 0 0'
                                                                        },
                                                                        {
                                                                            xtype: 'container',
                                                                            padding: '10 0',
                                                                            items: [
                                                                                {
                                                                                    xtype: 'label',
                                                                                    padding: '0 5 0 0',
                                                                                    text: '題名:'
                                                                                },
                                                                                {
                                                                                    xtype: 'label',
                                                                                    itemId: 'lblMsgTitle',
                                                                                    padding: '0 5 0 0'
                                                                                }
                                                                            ]
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    xtype: 'container',
                                                                    height: 50,
                                                                    margin: '0 -5 0 0',
                                                                    layout: {
                                                                        type: 'hbox',
                                                                        align: 'stretch',
                                                                        pack: 'end',
                                                                        padding: '5 0 5 5'
                                                                    },
                                                                    items: [
                                                                        {
                                                                            xtype: 'button',
                                                                            margins: '',
                                                                            itemId: 'btnAttach',
                                                                            width: 60,
                                                                            icon: 'resources/images/attachment.png',
                                                                            iconAlign: 'top',
                                                                            text: '添付'
                                                                        },
                                                                        {
                                                                            xtype: 'button',
                                                                            margins: '0 5 0 5',
                                                                            disabled: true,
                                                                            id: 'btnFavorite',
                                                                            itemId: 'btnFavorite',
                                                                            width: 60,
                                                                            icon: 'resources/images/s_favorite.ico',
                                                                            iconAlign: 'top',
                                                                            text: '追加',
                                                                            tooltip: 'Ctr + F3'
                                                                        },
                                                                        {
                                                                            xtype: 'button',
                                                                            disabled: true,
                                                                            itemId: 'btnEditMessage',
                                                                            margin: '0 5 0 0',
                                                                            padding: '0 10',
                                                                            width: 60,
                                                                            icon: 'resources/images/edit-icon.ico',
                                                                            iconAlign: 'top',
                                                                            text: '編集'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'panel',
                                                            flex: 1,
                                                            region: 'north',
                                                            border: false,
                                                            height: 150,
                                                            layout: 'fit',
                                                            items: [
                                                                {
                                                                    xtype: 'textareafield',
                                                                    itemId: 'txtMsg',
                                                                    margin: '0 0 0 -1',
                                                                    readOnly: true
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'panel',
                                                            flex: 1,
                                                            region: 'center',
                                                            border: false,
                                                            layout: 'border',
                                                            items: [
                                                                {
                                                                    xtype: 'panel',
                                                                    region: 'center',
                                                                    border: false,
                                                                    layout: 'fit',
                                                                    items: [
                                                                        {
                                                                            xtype: 'gridpanel',
                                                                            border: false,
                                                                            height: 100,
                                                                            id: 'grdMsgComment',
                                                                            itemId: 'grdMsgComment',
                                                                            autoScroll: true,
                                                                            bodyStyle: {
                                                                                'border-right': '1px'
                                                                            },
                                                                            forceFit: true,
                                                                            store: 'StMessageComments',
                                                                            viewConfig: {
                                                                                enableTextSelection: true
                                                                            },
                                                                            columns: [
                                                                                {
                                                                                    xtype: 'gridcolumn',
                                                                                    width: 200,
                                                                                    dataIndex: 'ADD_TIME',
                                                                                    text: '日時'
                                                                                },
                                                                                {
                                                                                    xtype: 'gridcolumn',
                                                                                    width: 450,
                                                                                    dataIndex: 'COMMENT_TEXT',
                                                                                    text: 'コメント'
                                                                                },
                                                                                {
                                                                                    xtype: 'gridcolumn',
                                                                                    width: 150,
                                                                                    dataIndex: 'EMP_NAME',
                                                                                    text: '名前'
                                                                                }
                                                                            ]
                                                                        }
                                                                    ]
                                                                }
                                                            ],
                                                            dockedItems: [
                                                                {
                                                                    xtype: 'container',
                                                                    dock: 'bottom',
                                                                    padding: 5,
                                                                    layout: 'column',
                                                                    items: [
                                                                        {
                                                                            xtype: 'textfield',
                                                                            columnWidth: 0.8,
                                                                            id: 'txtComment',
                                                                            itemId: 'txtComment',
                                                                            fieldLabel: 'コメント',
                                                                            labelWidth: 50,
                                                                            enableKeyEvents: true
                                                                        },
                                                                        {
                                                                            xtype: 'button',
                                                                            id: 'btnAddComment',
                                                                            itemId: 'btnAddComment',
                                                                            margin: '0 0 0 5',
                                                                            width: 60,
                                                                            icon: 'resources/images/comment.ico',
                                                                            text: '保存',
                                                                            tooltip: 'Shift + Enter'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'panel',
                                                    border: false,
                                                    width: 150,
                                                    layout: 'border',
                                                    bodyBorder: false,
                                                    items: [
                                                        {
                                                            xtype: 'container',
                                                            region: 'north',
                                                            height: 50,
                                                            items: [
                                                                {
                                                                    xtype: 'button',
                                                                    itemId: 'btnConfirm',
                                                                    margin: '15 10 0 0',
                                                                    style: {
                                                                        float: 'right'
                                                                    },
                                                                    icon: 'resources/images/check.ico',
                                                                    text: 'チェック'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'panel',
                                                            region: 'center',
                                                            border: false,
                                                            margin: '0 0 0 10',
                                                            layout: 'fit',
                                                            items: [
                                                                {
                                                                    xtype: 'gridpanel',
                                                                    border: false,
                                                                    itemId: 'grdMsgFlag',
                                                                    autoScroll: true,
                                                                    titleAlign: 'center',
                                                                    forceFit: true,
                                                                    hideHeaders: true,
                                                                    store: 'StMessageFlags',
                                                                    columns: [
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            dataIndex: 'EMP_NAME',
                                                                            text: 'EMP_NAME'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    border: false,
                    hidden: true,
                    itemId: 'pnlLogin',
                    bodyStyle: {
                        background: '#f6f6f6'
                    },
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            maxWidth: 500,
                            manageHeight: false,
                            items: [
                                {
                                    xtype: 'form',
                                    border: false,
                                    itemId: 'frmLogin',
                                    maxWidth: 500,
                                    layout: 'auto',
                                    title: 'ACcommunicator  ログイン',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            border: false,
                                            padding: 30,
                                            bodyBorder: false,
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    itemId: 'cboSection',
                                                    margin: '5 0',
                                                    width: 300,
                                                    fieldLabel: '部署名',
                                                    labelWidth: 120,
                                                    name: 'cboSection',
                                                    editable: false,
                                                    displayField: 'EMP_SECTION_NAME',
                                                    queryMode: 'local',
                                                    store: 'StSectionMasters',
                                                    valueField: 'EMP_SECTION_ID'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    itemId: 'cboEmployee',
                                                    width: 300,
                                                    fieldLabel: 'スタッフ',
                                                    labelWidth: 120,
                                                    name: 'cboEmployee',
                                                    editable: false,
                                                    displayField: 'EMP_NAME',
                                                    queryMode: 'local',
                                                    store: 'StEmployees',
                                                    valueField: 'EMP_ID'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'txtPassword',
                                                    width: 300,
                                                    fieldLabel: 'パスワード',
                                                    labelWidth: 120,
                                                    name: 'txtPassword',
                                                    inputType: 'password',
                                                    enableKeyEvents: true,
                                                    enforceMaxLength: true,
                                                    maxLength: 16
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    id: 'txtPasswordSecret',
                                                    itemId: 'txtPasswordSecret',
                                                    width: 300,
                                                    fieldLabel: '秘密パスワード',
                                                    labelWidth: 120,
                                                    name: 'txtPasswordSecret',
                                                    inputType: 'password',
                                                    enableKeyEvents: true,
                                                    enforceMaxLength: true,
                                                    maxLength: 16
                                                }
                                            ],
                                            dockedItems: [
                                                {
                                                    xtype: 'panel',
                                                    dock: 'bottom',
                                                    border: false,
                                                    margin: '10 0 0 0',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            margins: '10 10 0 0',
                                                            itemId: 'btnLogin',
                                                            width: 100,
                                                            text: 'ログイン'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'menu',
                    floating: false,
                    height: 85,
                    hidden: true,
                    id: 'ctxMenu',
                    itemId: 'ctxMenu',
                    maxHeight: 85,
                    maxWidth: 120,
                    style: {
                        'z-index': '1000 !important'
                    },
                    width: 120,
                    items: [
                        {
                            xtype: 'menuitem',
                            id: 'menuItemAddFavorite',
                            itemId: 'menuItemAddFavorite',
                            icon: 'resources/images/s_favorite.ico',
                            text: 'お気に入りに追加'
                        },
                        {
                            xtype: 'menuitem',
                            id: 'menuItemDeleteFavorite',
                            itemId: 'menuItemDeleteFavorite',
                            icon: 'resources/images/s_release.ico',
                            text: 'お気に入りから削除'
                        },
                        {
                            xtype: 'menuitem',
                            id: 'menuItemChangeStatus',
                            itemId: 'menuItemChangeStatus',
                            style: {
                                'z-index': '1000 !important'
                            },
                            text: '進捗変更',
                            menu: {
                                xtype: 'menu',
                                id: 'menuChangeStatus',
                                itemId: 'menuChangeStatus',
                                width: 120,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        id: 'menuItemStatusActive',
                                        text: '伝達中'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        id: 'menuItemStatusFinish',
                                        itemId: 'menuItemStatusFinish',
                                        text: '完了'
                                    }
                                ]
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});