/*
 * File: app/view/UcMessageDestinationPart.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.UcMessageDestinationPart', {
    extend: 'Ext.panel.Panel',

    requires: [
        'Ext.tree.Panel',
        'Ext.tree.View'
    ],

    border: false,
    height: 300,
    itemId: 'ucMessageDestinationPart',
    width: 200,
    layout: 'absolute',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            bodyStyle: {
                background: '#DFE8F6'
            },
            items: [
                {
                    xtype: 'treepanel',
                    height: 300,
                    viewConfig: {
                        enableTextSelection: false
                    }
                }
            ]
        });

        me.callParent(arguments);
    }

});