/*
 * File: app/store/StAddressCircle.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HKD.store.StAddressCircle', {
    extend: 'Ext.data.Store',

    requires: [
        'HKD.model.MdCircle'
    ],

    config: {
        data: [
            //{"id":null,"value":null,"name":null},
            {
                id: '1',
                name: '送信先',
                value: 'address'
            },
            //address
            {
                id: '2',
                name: 'サークル',
                value: 'circle'
            }
            //circle
        ],
        model: 'HKD.model.MdCircle',
        storeId: 'StAddressCircle'
    }
});