/*
 * File: app/store/StListSchedule.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HKD.store.StListSchedule', {
    extend: 'Ext.data.Store',

    requires: [
        'HKD.model.MdListSchedule'
    ],

    config: {
        data: [
            {
                STAFF_NAME: '浦○罰貴',
                DEPT_NAME: '役員',
                TASK_NAME: '定期会議ー会議室Ａ',
                START_TIME: '2014/01/01 08:00',
                END_TIME: '2014/01/01 13:00'
            },
            {
                STAFF_NAME: '浦○罰貴',
                DEPT_NAME: 'WEBマーケティング -> PM',
                TASK_NAME: '定期会議ー会議室Ａ',
                START_TIME: '2014/01/01 08:00',
                END_TIME: '2014/01/01 13:00'
            },
            {
                STAFF_NAME: '浦○罰貴',
                DEPT_NAME: 'WEBマーケティング -> マーケッター',
                TASK_NAME: '定期会議ー会議室B',
                START_TIME: '2014/01/01 08:00',
                END_TIME: '2014/01/01 13:00'
            },
            {
                STAFF_NAME: '浦○罰貴',
                DEPT_NAME: 'ITソリューション -> IT（システム開発）',
                TASK_NAME: '定期会議ー会議室C',
                START_TIME: '2014/01/01 08:00',
                END_TIME: '2014/01/01 13:00'
            },
            {
                STAFF_NAME: '浦○罰貴',
                DEPT_NAME: 'デザイン',
                TASK_NAME: '定期会議ー会議室B',
                START_TIME: '2014/01/01 08:00',
                END_TIME: '2014/01/01 13:00'
            },
            
        ],
        model: 'HKD.model.MdListSchedule',
        storeId: 'StListSchedule'
    }
});