/*
 * File: app/store/StMessage.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HKD.store.StMessage', {
    extend: 'Ext.data.Store',

    requires: [
        'HKD.model.MdMessage'
    ],

    config: {
        data: [
            {
                id: null,
                value: null,
                name: null//選択する
            },
            {
                id: 1,
                value: 'RecvUnconfirmed',
                name: '未認証',
                //Send Incomplete
                type: 'S'
            },
            {
                id: 2,
                value: 'RecvAllExcludeTrash',
                name: '受信すべて',
                //Send All Exclude Trash
                type: 'S'
            },
            {
                id: 3,
                value: 'RecvAll',
                name: 'ゴミを含むすべて',
                //Send All
                type: 'S'
            },
            {
                id: 4,
                value: 'SendIncomplete',
                name: '伝達中',
                //Received Unconfirmed
                type: 'R'
            },
            {
                id: 5,
                value: 'SendAllExcludeTrash',
                name: '送信すべて',
                //Received All Exclude Trash
                type: 'R'
            },
            {
                id: 6,
                value: 'SendAll',
                name: 'ゴミを含むすべて',
                //Received All
                type: 'R'
            },
            {
                id: 7,
                value: '',
                name: 'お気に入りを表示',
                //Favorite Display
                type: 'F'
            },
            {
                id: 8,
                value: '',
                name: 'お気に入りに追加',
                //Favorite Add
                type: 'F'
            },
            {
                id: 9,
                value: '',
                name: 'お気に入りから削除',
                //Favorite Delete
                type: 'F'
            }
        ],
        model: 'HKD.model.MdMessage',
        storeId: 'StMessage'
    }
});