/*
 * File: app/store/StMessageType.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HKD.store.StMessageType', {
    extend: 'Ext.data.Store',

    requires: [
        'HKD.model.MdMessageType'
    ],

    config: {
        clearOnPageLoad: false,
        data: [
            {
                id: null,
                value: null,
                name: null//選択する
            },
            {
                id: 1,
                value: 'R',
                name: '受信メッセージ'//Received message
            },
            {
                id: 2,
                value: 'S',
                name: '送信メッセージ'//Send message
            },
            {
                id: 3,
                value: 'F',
                name: 'お気に入り'//Favorite message
            }
        ],
        model: 'HKD.model.MdMessageType',
        storeId: 'StMessageType'
    }
});