/*
 * File: app/store/StRecipients.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HKD.store.StRecipients', {
    extend: 'Ext.data.Store',

    requires: [
        'HKD.model.MdRecipients'
    ],

    config: {
        data: [
            {
                id: 1,
                department: 'デパートメント',
                staff: 'スタッフ 1'
            },
            {
                id: 2,
                department: 'デパートメント',
                staff: 'スタッフ 2'
            },
            {
                id: 3,
                department: 'デパートメント',
                staff: 'スタッフ 3'
            },
            {
                id: 4,
                department: 'デパートメント',
                staff: 'スタッフ 5'
            },
            {
                id: 5,
                department: 'デパートメント',
                staff: 'スタッフ 6'
            },
            {
                id: 6,
                department: 'デパートメント',
                staff: 'スタッフ 7'
            },
            {
                id: 7,
                department: 'デパートメント',
                staff: 'スタッフ 8'
            },
            {
                id: 8,
                department: 'デパートメント',
                staff: 'スタッフ 9'
            },
            {
                id: 9,
                department: 'デパートメント',
                staff: 'スタッフ 10'
            },
            {
                id: 10,
                department: 'デパートメント',
                staff: 'スタッフ 11'
            },
            {
                id: 11,
                department: 'デパートメント',
                staff: 'スタッフ 12'
            },
            {
                id: 12,
                department: 'デパートメント',
                staff: 'スタッフ 13'
            },
            {
                id: 13,
                department: 'デパートメント',
                staff: 'スタッフ 14'
            },
            {
                id: 14,
                department: 'デパートメント',
                staff: 'スタッフ 15'
            },
            {
                id: 15,
                department: 'デパートメント',
                staff: 'スタッフ 16'
            },
            {
                id: 16,
                department: 'デパートメント',
                staff: 'スタッフ 17'
            },
            {
                id: 17,
                department: 'デパートメント',
                staff: 'スタッフ 18'
            },
            {
                id: 18,
                department: 'デパートメント',
                staff: 'スタッフ 19'
            },
            
        ],
        model: 'HKD.model.MdRecipients',
        storeId: 'StRecipients'
    }
});