/*
 * File: app/controller/CMain.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HKD.controller.CMain', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            cpMessageAdvancedFilter: 'container#cpMessageAdvancedFilter',
            buttonAdvancedSearch: 'button#btnAdvancedSearch',
            buttonHideAdvancedSearch: 'button#btnHideAdvancedSearch',
            cpMessageFilter: 'container#cpMessageFilter',
            buttonMessageFilter: 'button#mybutton23',
            buttonHideMessageFilter: 'button#mybutton24',
            grdListMessage: 'grid#gridmessage',
            cpListMessage: 'container#mycontainer21',
            cpMessageFilterPanel: {
                autoCreate: true,
                selector: 'panel#cpMessageFilterPanel',
                xtype: 'cpMessageFilterPanel'
            }
        },

        control: {
            "button#btnAdvancedSearch": {
                tap: 'onButtonTapShowAdvancedSearch'
            },
            "button#btnHideAdvancedSearch": {
                tap: 'onButtonTapHideAdvancedSearch'
            },
            "button#mybutton23": {
                tap: 'onButtonTapShowMessageFilter'
            },
            "button#mybutton24": {
                tap: 'onButtonTapHideMessageFilter'
            },
            "container#mycontainer21": {
                initialize: 'onContainerShowListMessage'
            },
            "button#btnFilterMessage": {
                tap: 'onButtonTapShowFilterMessage'
            }
        }
    },

    onButtonTapShowAdvancedSearch: function(button, e, eOpts) {
        var cpAdvancedSearch = this.getCpMessageAdvancedFilter();
        cpAdvancedSearch.show();
        var messageSearch = this.getCpMessageFilter();
        messageSearch.hide();
        this.getButtonHideAdvancedSearch().hide();
        //alert(cpAdvancedSearch);
        this.getButtonHideAdvancedSearch().show();
        this.getButtonAdvancedSearch().hide();
    },

    onButtonTapHideAdvancedSearch: function(button, e, eOpts) {
        var cpAdvancedSearch = this.getCpMessageAdvancedFilter();
        cpAdvancedSearch.hide();
        var messageSearch = this.getCpMessageFilter();
        messageSearch.show();
        this.getButtonHideAdvancedSearch().hide();
        this.getButtonAdvancedSearch().show();
    },

    onButtonTapShowMessageFilter: function(button, e, eOpts) {

        var messageFilter = this.getCpMessageFilter();
        messageFilter.show();
        //alert(cpAdvancedSearch);
        this.getButtonHideMessageFilter().show();
        this.getButtonMessageFilter().hide();
        this.getButtonAdvancedSearch().show();
    },

    onButtonTapHideMessageFilter: function(button, e, eOpts) {
        var messageFilter = this.getCpMessageFilter();
            messageFilter.hide();
        //alert(cpAdvancedSearch);
        this.getButtonHideMessageFilter().hide();
        this.getButtonMessageFilter().show();
        this.getButtonHideAdvancedSearch().hide();
        this.getButtonAdvancedSearch().hide();
        var cpAdvancedSearch = this.getCpMessageAdvancedFilter();
        cpAdvancedSearch.hide();
    },

    onContainerShowListMessage: function(component, eOpts) {
        var stored = this.getGrdListMessage().getStore();
        stored.load(
            {
                params: {
                    start                  : 0,
                    limit                  : 2000,
                    pageSize:50,
                    currentPage:1,
                    totalPages: 'count'
                }
            });
        this.getGrdListMessage().refresh();
    },

    onButtonTapShowFilterMessage: function(button, e, eOpts) {
        var me = this;
        var popup = me.getCpMessageFilterPanel();
        popup.showBy(button,'tc-bc?');
    }

});