/*
 * File: app/controller/CucTreeMember.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.CucTreeMember', {
    extend: 'Ext.app.Controller',

    tvwMemberCheckChange: function(node, checked, eOpts) {
        MyApp.app.common.checkChange(node, checked);
        this.checkParentNode(node);
        //check parent node if all child node is checked


    },

    checkParentNode: function(node) {
        if(node.getDepth()>1)
        {
            p = node.parentNode;//
            var pChildCheckedCount = 0;
            p.suspendEvents();
            p.eachChild(function(c) {
                if (c.get('checked')){
                    pChildCheckedCount++;
                }
            });
            if(pChildCheckedCount==p.childNodes.length){
                p.set('checked', true);
            }
            else{
                p.set('checked', false);
            }
            this.checkParentNode(p);
            p.resumeEvents();
        }
    },

    init: function(application) {
        this.control({
            "#tvwMember": {
                checkchange: this.tvwMemberCheckChange
            }
        });
    }

});
