/*
 * File: app/model/MdEmployee.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HKD.model.MdEmployee', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'EMP_ID'
            },
            {
                name: 'EMP_NAME'
            },
            {
                name: 'EMP_KANA'
            },
            {
                name: 'EMP_ZIPCODE'
            },
            {
                name: 'EMP_ADDRESS'
            },
            {
                name: 'EMP_BIRTHDAY'
            },
            {
                name: 'EMP_TELEPHONE'
            },
            {
                name: 'EMP_EMGADDRESS'
            },
            {
                name: 'EMP_MAILADDR'
            },
            {
                name: 'EMP_MOBILEMAILADDR'
            },
            {
                name: 'EMP_CARDISTANCE'
            },
            {
                name: 'EMP_BFEMPLOYEE'
            },
            {
                name: 'EMP_JOIN_COMPANY'
            },
            {
                name: 'EMP_JOIN_INSURANCE'
            },
            {
                name: 'EMP_PENSION_CODE'
            },
            {
                name: 'EMP_REMARKS'
            },
            {
                name: 'EMP_ACTIVE'
            },
            {
                name: 'EMP_AUTH_ID'
            },
            {
                name: 'EMP_SECTION_ID'
            },
            {
                name: 'AUTH_PROJECT_EDIT'
            },
            {
                name: 'CLASS_POINT'
            },
            {
                name: 'AC_PERMISSION'
            },
            {
                name: 'PROJECT_PERMISSION'
            },
            {
                name: 'WEB_PERMISSION'
            },
            {
                name: 'EMP_RETIRE_COMPANY'
            },
            {
                name: 'EMP_CTIID'
            }
        ]
    }
});