/*
 * File: app/model/MdListMessage.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HKD.model.MdListMessage', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'ATTACH',
                type: 'auto'
            },
            {
                name: 'MSG_ID'
            },
            {
                name: 'IMPORTANT_LEVEL'
            },
            {
                name: 'MSG_TITLE'
            },
            {
                name: 'RELEASE_DATE'
            },
            {
                name: 'EXPILATION_DATE'
            },
            {
                name: 'COMMENTDATE'
            },
            {
                name: 'EMP_NAME'
            },
            {
                name: 'EMP_PROGRESS_TEXT'
            },
            {
                name: 'DISP_STATUS'
            },
            {
                name: 'ATTACH_FLG'
            },
            {
                name: 'ADD_EMP_ID'
            }
        ]
    }
});