/*
 * File: app/model/MdSectionMaster.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HKD.model.MdSectionMaster', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'EMP_SECTION_ID'
            },
            {
                name: 'EMP_HIGHSECTION_ID'
            },
            {
                name: 'EMP_SECTION_NAME'
            },
            {
                name: 'EMP_SECTION_START'
            },
            {
                name: 'EMP_SECTION_END'
            },
            {
                name: 'EMP_SECTION_ACTIVE'
            },
            {
                name: 'EMP_DISPLAY_ORDER'
            },
            {
                name: 'EMP_SECTION_DEPTH'
            },
            {
                name: 'EMP_PARENT_SECTION_ID'
            }
        ]
    }
});