/*
 * File: app/store/StGroupMember.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.StGroupMember', {
    extend: 'Ext.data.Store',
    alias: 'store.StGroupMember',

    requires: [
        'MyApp.model.MdCustomGroup',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.util.Sorter'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'MyApp.model.MdCustomGroup',
            sortOnLoad: false,
            storeId: 'StGroupMember',
            sortOnFilter: false,
            proxy: {
                type: 'ajax',
                url: 'master/LoadGroupEmployeeBySchedules',
                reader: {
                    type: 'json',
                    root: 'data'
                }
            },
            sorters: {
                direction: 'DESC',
                property: 'CUSTOM_ID'
            }
        }, cfg)]);
    }
});