/*
 * File: app/view/CpAddEditMessage.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HKD.view.CpAddEditMessage', {
    extend: 'Ext.Container',
    alias: 'widget.cpAddEditMessage',

    requires: [
        'HKD.view.UCEmployees',
        'Ext.form.FieldSet',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Button',
        'Ext.field.TextArea'
    ],

    config: {
        itemId: 'cpAddEditMessage',
        layout: 'fit',
        scrollable: true,
        items: [
            {
                xtype: 'fieldset',
                scrollable: true,
                title: '',
                items: [
                    {
                        xtype: 'selectfield',
                        id: 'cboFrmAddMsgFixedForm',
                        label: 'テンプレート',
                        labelWidth: '35%',
                        displayField: 'TITLE',
                        store: 'StFixedForm',
                        valueField: 'VALUE'
                    },
                    {
                        xtype: 'textfield',
                        id: 'txtFrmAddMsgReleaseDate',
                        itemId: 'txtFrmAddMsgReleaseDate',
                        label: 'リリース日',
                        labelWidth: '35%',
                        readOnly: true
                    },
                    {
                        xtype: 'datepickerfield',
                        id: 'dtpFrmAddMsgExpilationDate',
                        itemId: 'dtpFrmAddMsgExpilationDate',
                        label: '伝達期限',
                        labelWidth: '35%',
                        dateFormat: 'Y/m/d',
                        picker: {
                            slotOrder: [
                                'year',
                                'month',
                                'day'
                            ]
                        }
                    },
                    {
                        xtype: 'selectfield',
                        id: 'cboFrmAddMsgImportant',
                        itemId: 'cboFrmAddMsgImportant',
                        label: '重要度',
                        labelWidth: '35%',
                        displayField: 'TITLE',
                        store: 'StCriticalLevels',
                        valueField: 'VALUE'
                    },
                    {
                        xtype: 'selectfield',
                        id: 'cboFrmAddMsgProgress',
                        itemId: 'cboFrmAddMsgProgress',
                        label: '進捗',
                        labelWidth: '35%',
                        displayField: 'TITLE',
                        store: 'StProgresses',
                        valueField: 'VALUE'
                    },
                    {
                        xtype: 'textfield',
                        id: 'txtFrmAddMsgMsgTitle',
                        itemId: 'txtFrmAddMsgMsgTitle',
                        label: '題名',
                        labelWidth: '35%'
                    },
                    {
                        xtype: 'textareafield',
                        id: 'txtFrmAddMsgMsgText',
                        itemId: 'txtFrmAddMsgMsgText',
                        label: 'コンテンツ',
                        labelWidth: '35%'
                    },
                    {
                        xtype: 'selectfield',
                        id: 'cboFrmAddMsgReceiveType',
                        itemId: 'cboFrmAddMsgReceiveType',
                        label: '宛先',
                        labelWidth: '35%',
                        displayField: 'title',
                        options: [
                            {
                                value: 1,
                                title: '送信先'
                            },
                            {
                                value: 2,
                                title: 'サークル'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        id: 'gridRecipientsContainer',
                        itemId: 'gridRecipientsContainer',
                        items: [
                            {
                                xtype: 'ucemployees'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        hidden: true,
                        id: 'circleContainer',
                        itemId: 'circleContainer',
                        items: [
                            {
                                xtype: 'selectfield',
                                id: 'cboCircleGroup',
                                itemId: 'cboCircleGroup',
                                label: 'サークル',
                                labelWidth: '35%',
                                displayField: 'TITLE',
                                store: 'StCircleGroup',
                                valueField: 'VALUE'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        layout: {
                            type: 'hbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'button',
                                id: 'btnAddMessageSave',
                                itemId: 'btnAddMessageSave',
                                margin: '10 5',
                                ui: 'confirm',
                                width: '30%',
                                text: '保存'
                            },
                            {
                                xtype: 'button',
                                id: 'btnAddMessageClose',
                                itemId: 'btnAddMessageClose',
                                margin: '10 5',
                                ui: 'decline',
                                width: '30%',
                                text: '閉じる'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});