/*
 * File: app/view/CpChildListSchedule.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HKD.view.CpChildListSchedule', {
    extend: 'Ext.Container',
    alias: 'widget.cpChildListSchedule',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.field.DatePicker',
        'Ext.picker.Date'
    ],

    config: {
        id: 'cpChildListSchedule',
        itemId: 'cpChildListSchedule1',
        width: '100%',
        layout: 'fit',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                layout: {
                    type: 'hbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'button',
                        id: 'btnAddNewScheduler',
                        itemId: 'btnAddNewScheduler',
                        ui: 'plain',
                        iconCls: 'add'
                    },
                    {
                        xtype: 'button',
                        hidden: true,
                        id: 'btnCloseGroupSchedule',
                        itemId: 'btnCloseGroupSchedule',
                        ui: 'decline-round',
                        text: '閉じる'
                    },
                    {
                        xtype: 'button',
                        id: 'btnMonth',
                        itemId: 'btnMonth',
                        text: '日'
                    },
                    {
                        xtype: 'button',
                        id: 'btnWeek',
                        itemId: 'btnWeek',
                        text: '週'
                    },
                    {
                        xtype: 'button',
                        id: 'btnDay',
                        itemId: 'btnDay',
                        style: 'text-align:center',
                        text: '月'
                    },
                    {
                        xtype: 'datepickerfield',
                        docked: 'right',
                        id: 'dtpDate',
                        itemId: 'dtpDate',
                        width: 154,
                        required: true,
                        value: {
                            day: new Date().getDate(),
                            month: (new Date().getMonth()+1),
                            year: new Date().getFullYear()
                        },
                        placeHolder: 'yyyy/mm/dd',
                        dateFormat: 'Y/m/d',
                        picker: {
                            useTitles: true,
                            slotOrder: [
                                'year',
                                'month',
                                'day'
                            ],
                            yearFrom: 2010,
                            yearTo: 2020
                        }
                    },
                    {
                        xtype: 'selectfield',
                        docked: 'right',
                        id: 'cmbFilterScheduler',
                        itemId: 'cmbFilterScheduler',
                        width: 179,
                        displayField: 'GROUP_NAME',
                        store: 'StGroupMember',
                        valueField: 'CUSTOM_ID'
                    }
                ]
            }
        ]
    }

});