/*
 * File: app/view/CpCircle.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HKD.view.CpCircle', {
    extend: 'Ext.Container',
    alias: 'widget.cpCircle',

    requires: [
        'HKD.view.UCEmployees',
        'Ext.form.FieldSet',
        'Ext.field.Radio',
        'Ext.field.Select',
        'Ext.Button'
    ],

    config: {
        id: 'pnCircle',
        itemId: 'pnCircle',
        scrollable: true,
        items: [
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'radiofield',
                        itemId: 'rdoAddCase',
                        label: '新規',
                        labelWidth: '35%',
                        name: 'mode',
                        checked: true
                    },
                    {
                        xtype: 'radiofield',
                        itemId: 'rdoEditCase',
                        label: '編集',
                        labelWidth: '35%',
                        name: 'mode'
                    },
                    {
                        xtype: 'selectfield',
                        disabled: true,
                        itemId: 'cmbListCircle',
                        label: 'リスト選択',
                        labelWidth: '35%',
                        displayField: 'TITLE',
                        valueField: 'VALUE'
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'txtGroupCircle',
                        label: 'サークル',
                        labelWidth: '35%'
                    },
                    {
                        xtype: 'container',
                        id: 'ctnBeforeCircle',
                        itemId: 'ctnBeforeCircle',
                        items: [
                            {
                                xtype: 'container',
                                itemId: 'mycontainer9',
                                items: [
                                    {
                                        xtype: 'ucemployees'
                                    }
                                ]
                            },
                            {
                                xtype: 'selectfield',
                                id: 'cmbRole',
                                itemId: 'cmbRole',
                                label: '役割',
                                readOnly: false,
                                displayField: 'TITLE',
                                store: 'StRoleCircle',
                                valueField: 'VALUE'
                            },
                            {
                                xtype: 'container',
                                layout: {
                                    type: 'hbox',
                                    align: 'center',
                                    pack: 'center'
                                },
                                items: [
                                    {
                                        xtype: 'button',
                                        id: 'btnAddGroup',
                                        itemId: 'btnAddGroup',
                                        margin: '10 5 10 5',
                                        ui: 'confirm',
                                        width: '45%',
                                        text: '加算'
                                    },
                                    {
                                        xtype: 'button',
                                        hidden: true,
                                        itemId: 'btnDeleteCircle',
                                        margin: '10 5 10 5',
                                        ui: 'action',
                                        width: '45%',
                                        text: '削除'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        hidden: true,
                        id: 'ctnAfterCircle',
                        itemId: 'ctnAfterCircle',
                        items: [
                            {
                                xtype: 'fieldset',
                                id: 'fstListEmployeeAfter',
                                itemId: 'fstListEmployeeAfter',
                                title: 'サークル選択'
                            },
                            {
                                xtype: 'container',
                                layout: {
                                    type: 'hbox',
                                    align: 'center',
                                    pack: 'center'
                                },
                                items: [
                                    {
                                        xtype: 'button',
                                        id: 'btnBackCircle',
                                        itemId: 'btnBackCircle',
                                        margin: '10 5 10 5',
                                        ui: 'action',
                                        width: '30%',
                                        text: 'バック'
                                    },
                                    {
                                        xtype: 'button',
                                        itemId: 'btnSaveCircle',
                                        margin: '10 5 10 5',
                                        ui: 'confirm',
                                        width: '30%',
                                        text: '保存'
                                    },
                                    {
                                        xtype: 'button',
                                        itemId: 'btnCloseCircle',
                                        margin: '10 5 10 5',
                                        ui: 'decline',
                                        width: '30%',
                                        text: '閉じる'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});