/*
 * File: app/view/CpListMessage.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HKD.view.CpListMessage', {
    extend: 'Ext.Container',
    alias: 'widget.cpListMessage',

    requires: [
        'Ext.Button',
        'Ext.grid.Grid',
        'Ext.grid.plugin.PagingToolbar',
        'Ext.grid.column.Template',
        'Ext.XTemplate'
    ],

    config: {
        itemId: 'mycontainer21',
        width: '100%',
        layout: 'vbox',
        items: [
            {
                xtype: 'button',
                hidden: true,
                itemId: 'mybutton23',
                style: 'color:blue; font-size: 100%;',
                ui: 'plain',
                text: 'メッセージフィルター'
            },
            {
                xtype: 'button',
                hidden: true,
                itemId: 'mybutton24',
                style: 'color:blue; font-size: 100%;',
                ui: 'plain',
                text: 'メッセージフィルター非表示'
            },
            {
                xtype: 'grid',
                titleBar: false,
                flex: 1,
                id: 'gridmessage',
                itemId: 'gridmessage',
                width: '100%',
                store: 'StListMessage',
                itemHeight: 40,
                title: 'メッセージ一覧',
                plugins: [
                    {
                        type: 'gridpagingtoolbar'
                    }
                ],
                columns: [
                    {
                        xtype: 'templatecolumn',
                        tpl: [
                            '{ATTACH}'
                        ],
                        width: 62,
                        text: '添付'
                    },
                    {
                        xtype: 'column',
                        width: 310,
                        dataIndex: 'MSG_TITLE',
                        text: '題名'
                    },
                    {
                        xtype: 'column',
                        width: 110,
                        align: 'center',
                        dataIndex: 'MSG_ID',
                        text: '伝達ID'
                    },
                    {
                        xtype: 'column',
                        width: 110,
                        align: 'center',
                        dataIndex: 'IMPORTANT_LEVEL',
                        text: '重要度'
                    },
                    {
                        xtype: 'column',
                        width: 120,
                        dataIndex: 'RELEASE_DATE',
                        text: '受信日時'
                    },
                    {
                        xtype: 'column',
                        width: 120,
                        dataIndex: 'EXPILATION_DATE',
                        text: '期限'
                    },
                    {
                        xtype: 'column',
                        width: 110,
                        dataIndex: 'COMMENTDATE',
                        text: '最終な更新日'
                    },
                    {
                        xtype: 'column',
                        width: 110,
                        dataIndex: 'EMP_NAME',
                        text: '送信者'
                    },
                    {
                        xtype: 'column',
                        width: 110,
                        dataIndex: 'EMP_PROGRESS_TEXT',
                        text: '進捗'
                    }
                ]
            }
        ]
    }

});