/*
 * File: app/view/CpLogin.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HKD.view.CpLogin', {
    extend: 'Ext.Container',
    alias: 'widget.cpLogin',

    requires: [
        'Ext.Img',
        'Ext.Label',
        'Ext.form.FieldSet',
        'Ext.field.Select',
        'Ext.field.Password',
        'Ext.Button'
    ],

    config: {
        id: 'ctnLogin',
        itemId: 'ctnLogin',
        layout: 'vbox',
        scrollable: true,
        items: [
            {
                xtype: 'image',
                height: 74,
                hidden: true,
                margin: '20 0 0 0',
                src: 'resources/sm/images/icons/login_64.png'
            },
            {
                xtype: 'label',
                hidden: true,
                hideAnimation: 'fadeOut',
                html: 'Login failed. Please enter the correct credentials.',
                itemId: 'signInFailedLabel',
                showAnimation: 'fadeIn',
                style: 'color:#990000;margin:5px 0px;'
            },
            {
                xtype: 'fieldset',
                title: 'ログイン HKD',
                items: [
                    {
                        xtype: 'selectfield',
                        id: 'cmbSection',
                        itemId: 'cmbSection',
                        labelAlign: 'top',
                        placeHolder: '部署名',
                        autoSelect: false,
                        displayField: 'EMP_SECTION_NAME',
                        store: 'StSectionMaster',
                        valueField: 'EMP_SECTION_ID'
                    },
                    {
                        xtype: 'selectfield',
                        id: 'cmbEmployee',
                        itemId: 'cmbEmployee',
                        labelAlign: 'top',
                        required: true,
                        placeHolder: 'スタッフ',
                        autoSelect: false,
                        displayField: 'EMP_NAME',
                        store: 'StEmployee',
                        valueField: 'EMP_ID'
                    },
                    {
                        xtype: 'passwordfield',
                        id: 'txtPassword',
                        itemId: 'txtPassword',
                        name: 'passwordTextField',
                        value: 0,
                        placeHolder: 'パスワード'
                    },
                    {
                        xtype: 'passwordfield',
                        id: 'txtPasswordSecret',
                        itemId: 'txtPasswordSecret',
                        value: 0,
                        placeHolder: '秘密パスワード'
                    }
                ]
            },
            {
                xtype: 'container',
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'button',
                        id: 'btnLogin',
                        itemId: 'btnLogin',
                        padding: '10px',
                        ui: 'action-round',
                        width: '50%',
                        text: 'ログイン'
                    }
                ]
            }
        ]
    }

});