/*
 * File: app/view/CpMessageFilterPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HKD.view.CpMessageFilterPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.cpMessageFilterPanel',

    requires: [
        'HKD.view.CpMessageFilter',
        'HKD.view.CpMessageAdvancedFilter',
        'HKD.view.CpActionContainer',
        'Ext.Container'
    ],

    config: {
        hidden: true,
        itemId: 'cpMessageFilterPanel',
        left: '5%',
        padding: 10,
        top: '0%',
        hideOnMaskTap: true,
        layout: 'vbox',
        modal: true,
        items: [
            {
                xtype: 'cpMessageFilter'
            },
            {
                xtype: 'cpMessageAdvancedFilter',
                hidden: true
            },
            {
                xtype: 'cpActionContainer'
            }
        ]
    }

});