/*
 * File: app/view/CpMessageFilter.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HKD.view.CpMessageFilter', {
    extend: 'Ext.Container',
    alias: 'widget.cpMessageFilter',

    requires: [
        'Ext.field.Select'
    ],

    config: {
        itemId: 'cpMessageFilter',
        items: [
            {
                xtype: 'selectfield',
                itemId: 'myselectfield20',
                label: 'サークル別絞込',
                labelWrap: true,
                placeHolder: 'サークルを選んでください。',
                displayField: 'TITLE',
                store: 'StCircleGroup',
                valueField: 'VALUE'
            },
            {
                xtype: 'selectfield',
                itemId: 'messagetype',
                label: 'メッセージタイプ',
                labelWrap: true,
                placeHolder: 'メッセージタイプの選択',
                displayField: 'name',
                store: 'StMessageType'
            },
            {
                xtype: 'selectfield',
                id: 'message',
                itemId: 'message',
                label: 'メッセージステータス',
                labelWrap: true,
                name: 'message',
                placeHolder: 'メッセージ選択',
                readOnly: true,
                displayField: 'name',
                store: 'StMessage'
            }
        ]
    }

});