/*
 * File: app/view/CpNavigationToolbar.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HKD.view.CpNavigationToolbar', {
    extend: 'Ext.Toolbar',
    alias: 'widget.navigationBar',

    requires: [
        'Ext.Button'
    ],

    config: {
        cls: 'nav-bar',
        docked: 'top',
        minHeight: '44',
        items: [
            {
                xtype: 'button',
                cls: 'sidebar-btn',
                itemId: 'sidebarBtn',
                ui: 'plain',
                iconCls: 'list'
            },
            {
                xtype: 'button',
                docked: 'right',
                id: 'btnHome',
                itemId: 'btnHome',
                ui: 'plain',
                iconCls: 'home'
            },
            {
                xtype: 'button',
                id: 'btnFilterMessage',
                itemId: 'btnFilterMessage',
                ui: 'plain',
                iconCls: 'search'
            }
        ]
    }

});