/*
 * File: app/view/UCEmployees.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HKD.view.UCEmployees', {
    extend: 'Ext.Container',
    alias: 'widget.ucemployees',

    requires: [
        'Ext.field.Text',
        'Ext.grid.Grid',
        'Ext.grid.plugin.MultiSelection',
        'Ext.grid.column.Column'
    ],

    config: {
        itemId: 'ucEmployees',
        items: [
            {
                xtype: 'textfield',
                id: 'txtEmployees',
                itemId: 'txtEmployees',
                label: '送信先',
                labelWidth: '35%'
            },
            {
                xtype: 'grid',
                height: 400,
                itemId: 'gridEmployees',
                width: '100%',
                store: 'StEmployees',
                itemHeight: 40,
                title: '送信先 スタッフ',
                plugins: [
                    {
                        triggerText: '選択',
                        cancelText: 'キャンセル',
                        deleteText: '削除',
                        type: 'gridmultiselection'
                    }
                ],
                columns: [
                    {
                        xtype: 'column',
                        hidden: true,
                        width: 110,
                        align: 'center',
                        dataIndex: 'EMP_ID',
                        text: 'EMP_ID'
                    },
                    {
                        xtype: 'column',
                        minWidth: 200,
                        dataIndex: 'EMP_NAME',
                        text: 'スタッフ'
                    }
                ]
            }
        ]
    }

});